services:
  db:
    image: postgres:16.4
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cms_db
    networks:
      - my_bridge

  app:
    image: billdev1958/sanatorio-back:1.0
    depends_on:
      - db
    env_file:
      - ./sanatorio-back/.env
    restart: always
    expose:
      - "8080"
    networks:
      - my_bridge


  frontend:
    image: billdev1958/csm-pacientes:1.0
    depends_on:
      - app
    restart: always
    expose:
      - "80"
    networks:
      - my_bridge

        
  proxy:
    image: nginx:latest
    depends_on:
      - app
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    networks:
      - my_bridge

volumes:
  db_data:

networks:
  my_bridge:
    driver: bridge
