
services:

  db:
    image: postgres:16.4
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: university_db

  app:
    build:
      context: ./sanatorio-back
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./sanatorio-back/.env
    restart: always
