services:
  db:
    image: postgres:16.4
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: university_db

  app:
    build:
      context: ./sanatorio-back
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./sanatorio-back/.env
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./csm-pacientes
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"

volumes:
  db_data:
