services:
  db:
    image: postgres:16.4
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: university_db

  app:
    build:
      context: ./sanatorio-back
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./sanatorio-back/.env
    restart: always
    expose:
      - "8080"  # Exponer solo internamente para el proxy

  frontend:
    build:
      context: ./csm-pacientes
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: always
    expose:
      - "5173"  # Exponer en un puerto interno diferente para el proxy

  proxy:
    image: nginx:latest
    depends_on:
      - app
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Exponer el puerto 80 al exterior para el acceso HTTP
    restart: always

volumes:
  db_data:
