services:
  db:
    env_file:
      - ./.env.dev
    ports:
      - "5433:5432"

  app:
    image: billdev1958/sanatorio-back:dev
    env_file:
      - ./.env.dev
    volumes:
      - ./.env.dev:/app/.env:ro
    ports:
      - "8080:8080"


  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./csm-pacientes:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    env_file:
      - ./.env.dev
    ports:
      - "5173:5173"