services:
  db:
    image: postgres:16.4
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    networks:
      - my_bridge

  app:
    image: billdev1958/sanatorio-back:latest
    depends_on:
      - db
    restart: always
    expose:
      - "8080"
    networks:
      - my_bridge
    env_file:
      - .env.production
    volumes:
      - ./.env.production:/app/.env:ro

  frontend:
    image: billdev1958/csm-pacientes:latest
    depends_on:
      - app
    restart: always
    expose:
      - "80"
    networks:
      - my_bridge
    env_file:
      - .env.production
    environment:
      - VITE_BACKEND_HOST=${VITE_BACKEND_HOST}

  proxy:
    image: nginx:latest
    depends_on:
      - app
      - frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - my_bridge
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./.env.production:/etc/nginx/.env:ro
      - ./entrypoint.sh:/docker-entrypoint.d/99-entrypoint.sh:ro
    environment:
      - VITE_BACKEND_HOST=${VITE_BACKEND_HOST}
      - VITE_FRONTEND_HOST=${VITE_FRONTEND_HOST}

volumes:
  db_data:

networks:
  my_bridge:
    driver: bridge
