# Imagen base con Go y herramientas de desarrollo
FROM golang:1.24.0 AS dev

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar Air para hot reload
RUN go install github.com/air-verse/air@latest

COPY internal/domain/email/plantillaConfirmacion.html email/
COPY internal/domain/email/plantillaConfirmacionC.html email/

COPY internal/domain/email/logo.png email/
COPY internal/domain/email/logo_cms.png email/

# Copiar dependencias primero (para aprovechar la caché)
COPY go.mod go.sum ./
RUN go mod download

# Copiar el código fuente
COPY . .

# Comando de desarrollo con hot reload
CMD ["air"]
